py_test(
    name = "check_java_identifier_case_test",
    srcs = [
        "check_java_identifier_case.py",
    ],
    main = "check_java_identifier_case.py",
    data = [
        "//src/main/java/org/owasp/url:srcs",
    ]
)
